### ISSUE TITLE
Feature request: Add `lobste.rs` 

### ISSUE THREAD

**Issue by g-berthiaume** [benwinding/newsit#13]
[Lobsters](https://lobste.rs/) is a computing-focused community centred around link aggregation and discussion.
IMO, It's one of the best tech discussions on the internet.

Thank you for maintaining Newsit. It's great.

**Comment by benwinding** [comment]
Hey @g-berthiaume,
Glad to hear you like it! Lobsters has actually been requested before and I left [a very detailed response here](https://github.com/benwinding/newsit/issues/12)  
Basically, it doesn't have an API and includes CORS protection, making it impossible for clients to search the site from a browser extension. 
If you know of a free API for lobsters let me know! 👍

**Comment by g-berthiaume** [comment]
Ah my apologies for the issue duplication.
