### ISSUE TITLE
New Reddit links

### ISSUE THREAD

**Issue by dance2die** [benwinding/newsit#14]
Can I request to configure to show old/new reddit links?

Relevant code - 
https://github.com/benwinding/newsit/blob/master/src/js/background/reddit.ts#L20

**Comment by benwinding** [comment]
We need to use "old.reddit" to search for links, as the new Reddit has CORS enabled.

But we could probably convert links to the new reddit, let me have a go 🤔🤔🤔

**Comment by dance2die** [comment]
Thank you~👍 

That's what I wanted :). A new reddit link when I open in the browser 😄

**Comment by benwinding** [comment]
Should be available in Newsit "2.1.1" ... whenever it's approved and available!
