### ISSUE TITLE
Lack of a license

### ISSUE THREAD

**Issue by bminusl** [benwinding/newsit#5]
I maintain an [awesome](https://github.com/topics/awesome) list named [awesome-hackernews](https://github.com/bminusl/awesome-hackernews) where Hacker News related tools are featured.

I noticed `newsit` does not have a license. See [https://choosealicense.com/no-permission/](https://choosealicense.com/no-permission/).

Is this an oversight?

---

Also: [related issue](https://github.com/benwinding/ycomments/issues/2)

**Comment by benwinding** [comment]
Hi @bminusl,
Thanks for checking out my project! Yes, it was an oversight. Added MIT license to the rep :+1: 
Cheers,
Ben
