### ISSUE TITLE
Release notes at AMO

### ISSUE THREAD

**Issue by grahamperrin** [benwinding/newsit#6]
I see the collection of notes at https://addons.mozilla.org/en-GB/firefox/addon/newsit-hnews-and-reddit-links/

It'll be smart to have them instead at e.g. 

https://addons.mozilla.org/en-GB/firefox/addon/newsit-hnews-and-reddit-links/versions/2.0.3/updateinfo/

– for them to also appear in their proper place at about:addons

![image](https://user-images.githubusercontent.com/192271/111802763-4821aa00-88c6-11eb-8591-01c888207c5c.png)

– and then you can have the _Details_ areas given to general information about the extension (without release notes). 

Thanks

----

Looking back, https://addons.mozilla.org/en-GB/firefox/addon/newsit-hnews-and-reddit-links/versions/2.0.2/updateinfo/ was non-empty ☑

**Comment by benwinding** [comment]
Hi @grahamperrin, 
Great idea, but the firefox extension store doesn't seem to have an edit "Release Notes" feature... so unless I can assign release notes to each version, I don't want to remove it from the main description. 
I'll try and add the Release Notes to the next version though.
Cheers,
Ben

**Comment by benwinding** [comment]
Not sure if the developer portal has been updated, or I just missed the feature originally, but it seems to be possible now!

All versions now have the corresponding release notes :+1:

**Comment by grahamperrin** [comment]
Thank you! 

![image](https://user-images.githubusercontent.com/192271/114500193-7bcec600-9c1f-11eb-9351-ce1ad51dcf10.png)

![image](https://user-images.githubusercontent.com/192271/114500248-9012c300-9c1f-11eb-9110-85d5aed79f6a.png)
