### ISSUE TITLE
☐ Hide [+] When No Results: _found_ results maybe be hidden until after the box to hide _no_ results is checked ☑ then un-checked ☐

### ISSUE THREAD

**Issue by grahamperrin** [benwinding/newsit#9]
### Firefox `88.0.1`

https://drewdevault.com/2021/04/26/Cryptocurrency-is-a-disaster.html for example, I do get a result when I use Newsit in isolation, in a _test_ profile. 

Since I don't know when, I no longer get results in my heavily extended _default_ profile. There's no icon, of any sort, after actively checking a page. 

Please, what type of extension might be in conflict? 

Can I methodically identify a conflict without disabling ranges of extensions?

**Comment by grahamperrin** [comment]
### Chromium `90.0.4430.93`

The same symptom, no icon after clicking **Check Current Page**.

Tested: 

* https://drewdevault.com/2021/04/26/Cryptocurrency-is-a-disaster.html
* https://www.newscientist.com/article/2277076-green-bitcoin-alternative-chia-is-leading-to-hard-disc-shortages/ (pictured below)

![image](https://user-images.githubusercontent.com/192271/118248629-6f4ac100-b49c-11eb-8f76-e7e9a25603d4.png)

I have fewer extensions with Chromium. 

----

If there _is_ an extensions conflict, maybe it'll be useful to tell what (a) my default profile and (b) Chromium have in common …

**Comment by benwinding** [comment]
Hi @grahamperrin,

Unfortunately I can't determine what is conflicting from that information. 

I would recommend switching off extensions one by one in the manage extensions section in chrome, then seeing which ones block the newsit content icons.

Also, I like those articles, very interesting read and discussions!

Let me know how you go and I can see how to fix it.
Cheers, 
Ben

**Comment by grahamperrin** [comment]
I'm no longer certain of an extensions conflict. 

Chromium `90.0.4430.212 (Official Build) (64-bit)` on FreeBSD `CURRENT-14.0` with Newsit `2.0.4` alone enabled: 

* nothing appears after clicking **Check Current Page**. 

Tested: 

* https://drewdevault.com/2021/04/26/Cryptocurrency-is-a-disaster.html
* https://www.devever.net/~hl/freenode_abuse

**Comment by benwinding** [comment]
Thanks for responding and trying that. It doesn't seem to be the versioning or OS, rather a bug in Newsit when some options are enabled.

It can be replicated like this (video below)

![Peek 2021-05-23 13-58](https://user-images.githubusercontent.com/11782590/119248240-04e9fd00-bbcf-11eb-84dc-289b5c59b1d1.gif)

The "Hide [+] when no results" seems to be broken, I'll try and fix it in the next few days.

Cheers,
Ben

**Comment by grahamperrin** [comment]
Thanks! 

If it helps to diagnose a root cause, it's likely that I **never** opted to hide _no results_ in Chromium: 

* generally, I'd never need the option (because I never allow automated checks)
* I might have added the extension to Chromium solely for the purpose of diagnosing this issue.

**Comment by grahamperrin** [comment]
Hmm. Two examples. 

https://drewdevault.com/2021/04/26/Cryptocurrency-is-a-disaster.html 

* I can work around the issue in my _default_ Firefox profile, with scores of other extensions enabled ☑
* I can work around in Chromium, with most extensions re-enabled that were temporarily disabled for test purposes ☑

https://www.devever.net/~hl/freenode_abuse 

* I can work around in my default Firefox profile ☑
* I can **not** yet work around in Chromium, and disabling all other extensions does not help. 

For myself, I'm not bothered by the edge case (if that's what it is) in Chromium.

**Comment by benwinding** [comment]
Hi @grahamperrin,
Should be fixed in version `2.0.5` currently being deployed.
Let me know if there's any issues.
Cheers,
Ben
